### ISSUE TITLE
Why won't this download? Returns 401

### ISSUE THREAD

**Issue by mdsauce** [enriquegh/sauce-log-parser#28]
python sel_log_parser.py -a $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -u aditya.pochiraju 1a1534c524c344559685123120ee3aa8 3285e4c877254ab188c42bd738cde054 -v 

Output:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): saucelabs.com:443
DEBUG:urllib3.connectionpool:https://saucelabs.com:443 "GET /rest/v1/aditya.pochiraju/jobs/1a1534c524c344559685123120ee3aa8/assets/log.json HTTP/1.1" 401 None
Something went wrong. Try running with '-v'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): saucelabs.com:443
DEBUG:urllib3.connectionpool:https://saucelabs.com:443 "GET /rest/v1/aditya.pochiraju/jobs/3285e4c877254ab188c42bd738cde054/assets/log.json HTTP/1.1" 401 None
Something went wrong. Try running with '-v'
Could not download job id 1a1534c524c344559685123120ee3aa8
Could not download job id 3285e4c877254ab188c42bd738cde054

**Comment by enriquegh** [comment]
This my bad. Made a bug when I added the verbose output.
Was sending the username of the job owner instead of the username of the admin (i.e. -a)

Fix is here:
https://github.com/enriquegh/sauce-log-parser/pull/29

**Comment by enriquegh** [comment]
Changed merged. This should work.
Normally, I'd add a test to avoid this in the future but not sure how I'd check this without using something like vcrpy to mock requests.

Might need to be done in the future.

**Comment by mdsauce** [comment]
Thanks Enrique!
